# PedidosGo — Supabase
# Fase 2: migraciones, seed, auth y storage

project_id = "pedidosgo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15
seed.sql = "./seed.sql"

[db.migrations]
enabled = true

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3003"
additional_redirect_urls = [
  "http://localhost:3001",
  "http://localhost:3002",
  "http://localhost:3003",
  "http://localhost:3004"
]

[storage]
enabled = true

[realtime]
enabled = true
